- name: sending email play
  hosts: all
  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: dmeonavneet@gmail.com
        password: "rbfqhoincpyouxqk"
        to:
          - "nrathi@redhat.com"
        subject: Ansible Report
        body: System has been successfully Provisioned you can new look in browser.
